### ISSUE TITLE
Pretty URLs are not enabled by default as README says

### ISSUE THREAD

**Issue by axelboc** [netlify-labs/netlify-plugin-sitemap#12]
```
  # disable pretty URLS and keep `index.html` & trailing `.html` file references in paths
  prettyURLs = false
```

I found out this wasn't the case. I had to set `prettyURLs` to `true`.

**Comment by erezrokah** [comment]
> I found out this wasn't the case. I had to set `prettyURLs` to `true`.

Sorry for the late reply @axelboc, can you share a reproduction? How are you running the plugin?

This value is set to `true` in the plugin's manifest:
https://github.com/netlify-labs/netlify-plugin-sitemap/blob/1d417536742dc7d43c517b03a0b791099ec878d9/manifest.yml#L12

**Comment by axelboc** [comment]
Hey @erezrokah, I'm just using a `netlify.toml` file:

```toml
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  prettyURLs = true
```

Without the second part, URLs in the sitemap have `.html` extensions.
