### ISSUE TITLE
Plugin adds unwanted "server/page" paths to sitemap for next js app

### ISSUE THREAD

**Issue by codebarz** [netlify-labs/netlify-plugin-sitemap#84]
**Describe the bug**

Generated sitemap.xml has server path in page location for nextjs application.

**To Reproduce**

Steps to reproduce the behaviour:
1. Install plugin in netlify app via the plugin installer on netlify dashboard
2. Visit https://site.com/sitemap.xml

**Expected behaviour**

Rather than https://site.com/server/pages/signup, it should generate `<loc>` as https://site.com/signup

**Comment by ryanscherler** [comment]
Happening for me as well. Our SEO team picked up on the sitemap.xml output and just recently sent the issue my way. Ugh I hope this is fixed soon!

**Comment by rileymacisaac** [comment]
This is happening to me as well, and I can't exclude it for some reason.

**Comment by leobenkel** [comment]
I am also getting pages like `/server/pages/500` in my sitemap

**Comment by ryanscherler** [comment]
This worked for me on our next.js app:

`netlify.toml`

```toml
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  exclude = [
    './.next/server/**',
  ]
```
